import{a as g,i as m}from"./assets/vendor-qc4nlv7U.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const s of i.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function o(t){if(t.ep)return;t.ep=!0;const i=a(t);fetch(t.href,i)}})();async function v(){return(await g.get("https://furniture-store-v2.b.goit.study/api/categories")).data}const w=document.querySelector(".list-categories");function C(r){const e=r.map(a=>`
      <li class="list-categories-item" data-category-id="${a._id}">
              <p class="list-categories-name">${a.name}</p>
            </li>
      `).join("");w.innerHTML=e}function l(r){function e(a){const{images:o,name:t,price:i,color:s}=a;return` <li class="furniture-catalog-items">
          <img class="furniture-catalog-img" src="${o[0]}" alt="${t}" width="500px" />
          <h2 class="furniture-catalog-title">${t}</h2>
          <ul class='color-list'>
            ${s.map(b=>`<li class='color-items' style="background-color: ${b};"></li>`).join("")}
          </ul>
          <p class="furniture-catalog-price">${i} грн</p>
          <button class="furniture-catalog-btn" type="button">детальніше</button>
        </li>
        `}return r.map(e).join("")}async function f(r){return(await g.get("https://furniture-store-v2.b.goit.study/api/furnitures",{params:{page:r,limit:8}})).data}const u=document.querySelector(".furniture-catalog-list"),c=document.querySelector(".btn-load-more"),p=8;let n,M,d;async function y(){n=1;try{const r=await f(n),e=l(r.furnitures);u.innerHTML=e,d=Math.ceil(r.totalItems/p),L()}catch{}}async function S(r,e){try{const a=await getFurnitureByCategory(r,e),o=l(a.furnitures);u.innerHTML=o,d=Math.ceil(a.totalItems/p),L()}catch{}}c.addEventListener("click",h);async function h(){n+=1;try{if(!M){const r=await f(n),e=l(r.furnitures);u.insertAdjacentHTML("beforeend",e)}}catch{}}function L(){n>=d?c.disabled=!0:c.disabled=!1}const $=document.querySelector(".btn-load-more");document.addEventListener("DOMContentLoaded",async r=>{try{const e=await v(),a=[{_id:"all",name:"Всі товари"},...e];C(a),await y();const o=document.querySelector(".list-categories-item");o&&o.classList.add("active-item-category")}catch(e){m.error({message:"Sorry, помилка при завантаженні категорій. Please try again!",position:"topRight"}),console.error("Помилка при завантаженні категорій:",e)}});const P=document.querySelector(".list-categories");P.addEventListener("click",async r=>{const e=r.target.closest(".list-categories-item");if(!e)return;document.querySelectorAll(".list-categories-item").forEach(t=>t.classList.remove("active-item-category")),e.classList.add("active-item-category");const o=e.dataset.categoryId;try{o==="all"?(await y(),console.log("Показати всі товари")):(await S(o),console.log(`Показати товари категорії: ${o}`))}catch(t){m.error({message:"Sorry, помилка при завантаженні товарів за категорією. Please try again!",position:"topRight"}),console.error("Помилка при завантаженні товарів за категорією:",t)}return o});$.addEventListener("click",h);
//# sourceMappingURL=index.js.map
