import{a as m}from"./assets/vendor-_35Z3w6n.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(e){if(e.ep)return;e.ep=!0;const a=n(e);fetch(e.href,a)}})();async function b(){return(await m.get("https://furniture-store-v2.b.goit.study/api/categories")).data}const v=document.querySelector(".list-categories");function M(t){const o=t.map(n=>`
      <li class="list-categories-item" data-category-id="${n._id}">
              <p class="list-categories-name">${n.name}</p>
            </li>
      `).join("");v.innerHTML=o}function l(t){function o(n){const{images:r,name:e,price:a,color:s}=n;return` <li class="furniture-catalog-items">
          <img class="furniture-catalog-img" src="${r[0]}" alt="${e}" width="500px" />
          <h2 class="furniture-catalog-title">${e}</h2>
          <ul class='color-list'>
            ${s.map(h=>`<li class='color-items' style="background-color: ${h};"></li>`).join("")}
          </ul>
          <p class="furniture-catalog-price">${a} грн</p>
          <button class="furniture-catalog-btn" type="button">детальніше</button>
        </li>
        `}return t.map(o).join("")}async function g(t){return(await m.get("https://furniture-store-v2.b.goit.study/api/furnitures",{params:{page:t,limit:8}})).data}const u=document.querySelector(".furniture-catalog-list"),c=document.querySelector(".btn-load-more"),p=8;let i,S,d;async function f(){i=1;try{const t=await g(i),o=l(t.furnitures);u.innerHTML=o,d=Math.ceil(t.totalItems/p),L()}catch{}}async function q(t,o){try{const n=await getFurnitureByCategory(t,o),r=l(n.furnitures);u.innerHTML=r,d=Math.ceil(n.totalItems/p),L()}catch{}}c.addEventListener("click",y);async function y(){i+=1;try{if(!S){const t=await g(i),o=l(t.furnitures);u.insertAdjacentHTML("beforeend",o)}}catch{}}function L(){i>=d?c.disabled=!0:c.disabled=!1}document.querySelector(".loader");document.querySelector(".loader-overlay");const w=document.querySelector(".btn-load-more");document.addEventListener("DOMContentLoaded",async t=>{try{const o=await b(),n=[{_id:"all",name:"Всі товари"},...o];M(n),await f();const r=document.querySelector(".list-categories-item");r&&r.classList.add("active-item-category")}catch(o){iziToast.error({message:"Sorry, помилка при завантаженні категорій. Please try again!",position:"topRight"}),console.error("Помилка при завантаженні категорій:",o)}});const C=document.querySelector(".list-categories");C.addEventListener("click",async t=>{const o=t.target.closest(".list-categories-item");if(!o)return;document.querySelectorAll(".list-categories-item").forEach(e=>e.classList.remove("active-item-category")),o.classList.add("active-item-category");const r=o.dataset.categoryId;try{r==="all"?(await f(),console.log("Показати всі товари")):(await q(r),console.log(`Показати товари категорії: ${r}`))}catch(e){iziToast.error({message:"Sorry, помилка при завантаженні товарів за категорією. Please try again!",position:"topRight"}),console.error("Помилка при завантаженні товарів за категорією:",e)}return r});w.addEventListener("click",y);(()=>{const t={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};t.openModalBtn.addEventListener("click",o),t.closeModalBtn.addEventListener("click",o);function o(){t.modal.classList.toggle("is-open"),document.body.classList.add("menu-open")}document.addEventListener("keydown",n);function n(e){e.key==="Escape"&&r()}document.addEventListener("click",e=>{t.modal.classList.contains("is-open")&&!e.target.closest(".mobile-menu-container")&&!e.target.closest("[data-menu-open]")&&r()});function r(){t.modal.classList.remove("is-open"),document.body.classList.remove("menu-open")}})();
//# sourceMappingURL=index.js.map
